### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by yzhh029** [CarterLi/liburing4cpp#2]
uname -a
Linux linux55 5.5.0-050500rc7-generic #202001192030 SMP Mon Jan 20 01:33:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

liburing 
commit 783831a0548d3c702bd18746b5f425106f10e090 (HEAD -> master, origin/master, origin/HEAD)
Author: Jens Axboe <axboe@kernel.dk>
Date:   Tue Jan 21 08:47:19 2020 -0700

~/liburing4cpp/demo$ make bench
clang++-9 ./bench.cpp -o bench -O0 -g -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -Wall -fcoroutines-ts -stdlib=libc++ -std=c++17 -lc++ -lc++abi -I.. -I../fmt/include ../fmt/src/format.cc -luring
In file included from ./bench.cpp:6:
../io_service.hpp:503:19: error: invalid use of incomplete type '::statx'
        co_return ::statx(dfd, path, flags, mask, statxbuf);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/liburing.h:343:8: note: forward declaration of 'statx'
struct statx;
       ^
1 error generated.
Makefile:30: recipe for target 'bench' failed
make: *** [bench] Error 1

**Comment by CarterLi** [comment]
Thank you for your interest, and sorry I missed this issue.

But it works for me on my machine.

```
⋊> ~/l/demo on async ◦ make bench                                       09:29:48
clang++ ./bench.cpp -o bench -O0 -g -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -Wall -fcoroutines-ts -stdlib=libc++ -std=c++17 -lc++ -lc++abi -I.. -I../fmt/include ../fmt/src/format.cc -luring
⋊> ~/l/demo on async ◦ ll bench                                         09:29:56
-rwxr-xr-x 1 carter carter 4.8M 1月  27 09:29 bench*
⋊> ~/l/demo on async ◦  
```

[statx(2)](http://www.man7.org/linux/man-pages/man2/statx.2.html) is indeed a little strange. There is a function named `statx` but at a same time there is a `stuct statx` which has the same name with function `statx`. Since C++ allows omiting `struct` keyword when referencing a struct, it can be troublesome when referencing a function like that. I'll remove `statx` for now.

**Comment by CarterLi** [comment]
When benchmarking, please enable compiler optimization with `env CXXFLAGS="-O3 -flto -DNDEBUG -pthread" make`, and be sure posting your result here :)
